Notebook 1b final fixes
SNEE-ICS/PrimaryCareDemandAndCapacity pull request #59
Opened 2024-01-11 15:20 UTC by IbrahimKhan07

2024-01-12 10:32 UTC, AJarman requested changes
Please review comments and and revise markdown file.
Thanks
Andrew

2024-01-12 10:32 UTC, AJarman commented on staticWebsite/content/appointments_attended.md
> +This analysis draws its primary data from the comprehensive appointments dataset provided by NHS England. The dataset encompasses a substantial time span, ranging from April 2021 to August 2023. FY 2
Correct typo/ sentence please

2024-01-12 10:32 UTC, AJarman commented on staticWebsite/content/appointments_attended.md
> +- Noteworthy is the trajectory in 2022, where this variance intensifies. The National Average escalates from  579,332.27 to  608,099.22, a significant uptick, while the SNEE-ICB sees a comparably mod
Can we remove this please and just focus on rate of appointments missed

2024-01-15 10:18 UTC, IbrahimKhan07 commented on staticWebsite/content/appointments_attended.md
> +This analysis draws its primary data from the comprehensive appointments dataset provided by NHS England. The dataset encompasses a substantial time span, ranging from April 2021 to August 2023. FY 2
resolved

2024-01-15 10:19 UTC, IbrahimKhan07 commented on staticWebsite/content/appointments_attended.md
> +- Noteworthy is the trajectory in 2022, where this variance intensifies. The National Average escalates from  579,332.27 to  608,099.22, a significant uptick, while the SNEE-ICB sees a comparably mod
Just keeping the table as placeholder, to replace the rates with proportions in the next PR.

2024-01-16 09:39 UTC, merged